name: paypal_rest_api
description: Unofficial Dart bindings for the PayPal REST API.
environment:
  sdk: '>=2.0.0 <3.0.0'
version: 1.0.0-dev+2
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/paypal_dart
dependencies:
  http: ^0.12.0+2
  crypto: ^2.0.6